- name: Add both conversion hosts to inventory
  ansible.builtin.import_tasks: conv_hosts_inventory.yml

- name: Create folder for link keypairs
  ansible.builtin.file:
    path: "{{ os_migrate_conversion_link_keypair_private_path | dirname }}"
    state: directory
    mode: '0700'

- name: Generate a link keypair
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: "{{ os_migrate_conversion_link_keypair_private_path }}"
    ssh_key_type: rsa

- name: Wait for src conversion host reachability
  ansible.builtin.wait_for:
    port: 22
    host: "{{ hostvars['os_migrate_conv_src']['ansible_ssh_host'] }}"
    search_regex: OpenSSH
    sleep: 5
    timeout: 600
  retries: 10

- name: Wait for dst conversion host reachability
  ansible.builtin.wait_for:
    port: 22
    host: "{{ hostvars['os_migrate_conv_dst']['ansible_ssh_host'] }}"
    search_regex: OpenSSH
    sleep: 5
    timeout: 600
  retries: 10
